---
#[mandatory] kstat_modules: Array of kstat module definitions
#[mandatory] kstat_modules[].id: kstat module string
#[mandatory] kstat_modules[].kstat_names: Array of kstat name definitions
#[mandatory] kstat_modules[].kstat_names[].id: kstat name string
#[optional]  kstat_modules[].kstat_names[].label_string: string to be used
#            as the metric label. Default value: instance 
#[mandatory] kstat_modules[].kstat_names[].kstat_stats: Array of kstat statistic
#            definitions
#[mandatory] kstat_modules[].kstat_names[].kstat_stats[].id: kstat statistic string
#[optional]  kstat_modules[].kstat_names[].kstat_stats[].suffix: string to be added 
#            as the metric suffix. Default value: total
#[optional]  kstat_modules[].kstat_names[].kstat_stats[].help: string to be used as the
#            metric help
#[optional]  kstat_modules[].kstat_names[].kstat_stats[].scale_factor: number the metric 
#            value to be multiplied with before the final representation 

#Example:
#
#kstat_modules:
#  - id: cpu
#    kstat_names:
#      - id: sys
#        label_string: cpu
#        kstat_stats:
#          - id: bawrite
#          - id: modload
#          - id: cpu_ticks_idle
#            help: Ticks the CPU spent in idle mode
#          - id: cpu_ticks_kernel
#            help: Ticks the CPU spent in kernel mode
#            scale_factor: 1
#          - id: cpu_nsec_dtrace
#            suffix: seconds_total
#            help: Seconds the CPU spent in dtrace mode
#            scale_factor: 1e-9
#  - id: unix
#    kstat_names:
#      - id: system_pages
#        kstat_stats:
#          - id: pagesfree
#          - id: freemem
#          - id: availrmem
#      - id: pset
#        kstat_stats:
#          - id: avenrun_15min
#            suffix: percents
#            help: 15 min CPU load average

kstat_modules:
  - id: cpu
    kstat_names:
      - id: sys
        label_string: cpu
        kstat_stats:

          - id: bawrite
          - id: bread
          - id: dtrace_probes
          - id: intr
          - id: intrblk
          - id: intrthread
          - id: lread
          - id: lwrite
          - id: modload

          - id: cpu_ticks_idle
            help: Ticks the CPU spent in idle mode

          - id: cpu_ticks_kernel
            help: Ticks the CPU spent in kernel mode
            scale_factor: 1

          - id: cpu_ticks_user
            help: Ticks the CPU spent in user mode

          - id: cpu_ticks_wait
            help: Ticks the CPU spent in wait  mode

          - id: cpu_nsec_dtrace
            suffix: seconds_total
            help: Seconds the CPU spent in dtrace mode
            scale_factor: 1e-9

          - id: cpu_nsec_idle
            suffix: seconds_total
            help: Seconds the CPU spent in idle mode
            scale_factor: 1e-9

          - id: cpu_nsec_intr
            suffix: seconds_total
            help: Seconds the CPU spent in interrupt mode
            scale_factor: 1e-9

          - id: cpu_nsec_kernel
            suffix: seconds_total
            help: Seconds the CPU spent in kernel mode
            scale_factor: 1e-9

          - id: cpu_nsec_user
            suffix: seconds_total
            help: Seconds the CPU spent in user mode
            scale_factor: 1e-9

          - id: cpu_load_intr
            suffix: percents

          - id: cpumigrate
          - id: iowait
          - id: nthreads
          - id: syscall
          - id: sysexec
          - id: sysfork
          - id: sysread
          - id: sysvfork
          - id: syswrite
          - id: trap
          - id: idlethread
          - id: inv_swtch
          - id: mutex_adenters
          - id: xcalls

      - id: vm
        kstat_stats:
          - id: pgswapin
          - id: pgswapout

  - id: unix
    kstat_names:
      - id: system_pages
        kstat_stats:
          - id: pagesfree
          - id: pageslocked
          - id: pagestotal
          - id: physmem
          - id: freemem
          - id: availrmem

      - id: vminfo
        kstat_stats:
          - id: freemem
          - id: swap_alloc
          - id: swap_avail
          - id: swap_free
          - id: swap_resv
          - id: updates

      - id: pset
        kstat_stats:
          - id: avenrun_15min
            suffix: percents
            help: 15 min CPU load average

          - id: avenrun_5min
            suffix: percents
            help: 5 min CPU load average

          - id: avenrun_1min
            suffix: percents
            help: 1 min CPU load average

  - id: zfs
    kstat_names:
      - id: arcstats
        kstat_stats:
          - id:  access_skip
          - id:  anon_evictable_data
          - id:  anon_evictable_metadata
          - id:  anon_size
          - id:  arc_meta_limit
          - id:  arc_meta_max
          - id:  arc_meta_min
          - id:  arc_meta_used
          - id:  async_upgrade_sync
          - id:  c
          - id:  c_max
          - id:  c_min
          - id:  compressed_size
          - id:  data_size
          - id:  deleted
          - id:  demand_data_hits
          - id:  demand_data_misses
          - id:  demand_hit_predictive_prefetch
          - id:  demand_hit_prescient_prefetch
          - id:  demand_metadata_hits
          - id:  demand_metadata_misses
          - id:  evict_l2_cached
          - id:  evict_l2_eligible
          - id:  evict_l2_eligible_mfu
          - id:  evict_l2_eligible_mru
          - id:  evict_l2_ineligible
          - id:  evict_l2_skip
          - id:  evict_not_enough
          - id:  evict_skip
          - id:  hash_chain_max
          - id:  hash_chains
          - id:  hash_collisions
          - id:  hash_elements
          - id:  hash_elements_max
          - id:  hdr_size
          - id:  hits
          - id:  l2_abort_lowmem
          - id:  l2_asize
          - id:  l2_bufc_data_asize
          - id:  l2_bufc_metadata_asize
          - id:  l2_cksum_bad
          - id:  l2_data_to_meta_ratio
          - id:  l2_evict_l1cached
          - id:  l2_evict_lock_retry
          - id:  l2_evict_reading
          - id:  l2_feeds
          - id:  l2_free_on_write
          - id:  l2_hdr_size
          - id:  l2_hits
          - id:  l2_io_error
          - id:  l2_log_blk_asize
          - id:  l2_log_blk_avg_asize
          - id:  l2_log_blk_count
          - id:  l2_log_blk_writes
          - id:  l2_mfu_asize
          - id:  l2_misses
          - id:  l2_mru_asize
          - id:  l2_prefetch_asize
          - id:  l2_read_bytes
          - id:  l2_rebuild_asize
          - id:  l2_rebuild_bufs
          - id:  l2_rebuild_bufs_precached
          - id:  l2_rebuild_cksum_lb_errors
          - id:  l2_rebuild_dh_errors
          - id:  l2_rebuild_io_errors
          - id:  l2_rebuild_log_blks
          - id:  l2_rebuild_lowmem
          - id:  l2_rebuild_size
          - id:  l2_rebuild_success
          - id:  l2_rebuild_unsupported
          - id:  l2_rw_clash
          - id:  l2_size
          - id:  l2_write_bytes
          - id:  l2_writes_done
          - id:  l2_writes_error
          - id:  l2_writes_lock_retry
          - id:  l2_writes_sent
          - id:  memory_throttle_count
          - id:  metadata_size
          - id:  mfu_evictable_data
          - id:  mfu_evictable_metadata
          - id:  mfu_ghost_evictable_data
          - id:  mfu_ghost_evictable_metadata
          - id:  mfu_ghost_hits
          - id:  mfu_ghost_size
          - id:  mfu_hits
          - id:  mfu_size
          - id:  misses
          - id:  mru_evictable_data
          - id:  mru_evictable_metadata
          - id:  mru_ghost_evictable_data
          - id:  mru_ghost_evictable_metadata
          - id:  mru_ghost_hits
          - id:  mru_ghost_size
          - id:  mru_hits
          - id:  mru_size
          - id:  mutex_miss
          - id:  other_size
          - id:  overhead_size
          - id:  p
          - id:  prefetch_data_hits
          - id:  prefetch_data_misses
          - id:  prefetch_metadata_hits
          - id:  prefetch_metadata_misses
          - id:  size
          - id:  snaptime
          - id:  uncompressed_size 




