---
#node_kstat_cpu_sys_ticks_kernel_total
#kstat_modules[].id: kstat module string
#kstat_modules[].kstat_names: array of module representations
#kstat_modules[]kstat_names[].id kstat name string
#kstat_modules[]kstat_names[].kstat_stats: array of statistics representations
#kstat_modules[]kstat_names[].kstat_stats[].id: kstat statistic representation
#kstat_modules[]kstat_names[].kstat_stats[].suffix: metric suffix 
#       to be providedin the end of metric name.
#       NOTE: the final metric name would provided in the following way:
#         node_kstat_<kstat_module>_<kstat_name>_<kstat_statistic>_<suffix>
#kstat_modules[]kstat_names[].kstat_stats[].type: metric type (counter/gauge)
#kstat_modules[]kstat_names[].kstat_stats[].help: metric help
#kstat_modules[]kstat_names[].kstat_stats[].scale_factor: number the metric value to be 
#         multiplied with before the final representation 

kstat_modules:
  - id: cpu
    kstat_names:
      - id: sys
        kstat_stats:

          - id: bawrite
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: bread
            suffix: total
            type: counter
            help: 
            scale_factor: 

          - id: dtrace_probes
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: intr
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: intrblk
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: intrthread
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: lread
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: lwrite
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: modload
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: cpu_ticks_idle
            suffix: total
            type: counter
            help: Ticks the CPU spent in idle mode
            scale_factor: 1

          - id: cpu_ticks_kernel
            suffix: total
            type: counter
            help: Ticks the CPU spent in kernel mode
            scale_factor: 1

          - id: cpu_ticks_user
            suffix: total
            type: counter
            help: Ticks the CPU spent in user mode
            scale_factor: 1

          - id: cpu_ticks_wait
            suffix: total
            type: counter
            help: Ticks the CPU spent in wait  mode
            scale_factor: 1

          - id: cpu_nsec_dtrace
            suffix: seconds
            type: counter
            help: Seconds the CPU spent in dtrace mode
            scale_factor: 1e-9

          - id: cpu_nsec_idle
            suffix: seconds
            type: counter
            help: Seconds the CPU spent in idle mode
            scale_factor: 1e-9

          - id: cpu_nsec_intr
            suffix: seconds
            type: counter
            help: Seconds the CPU spent in interrupt mode
            scale_factor: 1e-9

          - id: cpu_nsec_kernel
            suffix: seconds
            type: counter
            help: Seconds the CPU spent in kernel mode
            scale_factor: 1e-9

          - id: cpu_nsec_user
            suffix: seconds
            type: counter
            help: Seconds the CPU spent in user mode
            scale_factor: 1e-9

          - id: cpu_load_intr
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: cpumigrate
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: iowait
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: nthreads
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: syscall
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: sysexec
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: sysfork
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: sysread
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: sysvfork
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: syswrite
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: trap
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: idlethread
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: inv_swtch
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: mutex_adenters
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: xcalls
            suffix: total
            type: counter
            help: 
            scale_factor: 1

      - id: vm
        kstat_stats:
          - id: pgswapin
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: pgswapout
            suffix: total
            type: counter
            help: 
            scale_factor: 1

  - id: unix
    kstat_names:
      - id: system_pages
        kstat_stats:

          - id: pagesfree
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: pageslocked
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: pagestotal
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: physmem
            suffix: total
            type: counter
            help: 
            scale_factor: 1


      - id: pset
        kstat_stats:

          - id: avenrun_15min
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: avenrun_5min
            suffix: total
            type: counter
            help: 
            scale_factor: 1

          - id: avenrun_1min
            suffix: total
            type: counter
            help: 
            scale_factor: 1
